export const COUNTRIES = [
  { code: 'AD', name: 'Andorra', urlAliases: ['ad', 'andorra'] },
  { code: 'AE', name: 'United Arab Emirates', urlAliases: ['ae', 'united-arab-emirates'] },
  { code: 'AF', name: 'Afghanistan', urlAliases: ['af', 'afghanistan'] },
  { code: 'AG', name: 'Antigua and Barbuda', urlAliases: ['ag', 'antigua-and-barbuda'] },
  { code: 'AI', name: 'Anguilla', urlAliases: ['ai', 'anguilla'] },
  { code: 'AL', name: 'Albania', urlAliases: ['al', 'albania'] },
  { code: 'AM', name: 'Armenia', urlAliases: ['am', 'armenia'] },
  { code: 'AN', name: 'Netherlands Antilles', urlAliases: ['an', 'netherlands-antilles'] },
  { code: 'AO', name: 'Angola', urlAliases: ['ao', 'angola'] },
  { code: 'AQ', name: 'Antarctica', urlAliases: ['aq', 'antarctica'] },
  { code: 'AR', name: 'Argentina', urlAliases: ['ar', 'argentina'] },
  { code: 'AS', name: 'American Samoa', urlAliases: ['as', 'american-samoa'] },
  { code: 'AT', name: 'Austria', urlAliases: ['at', 'austria'] },
  { code: 'AU', name: 'Australia', urlAliases: ['au', 'australia'] },
  { code: 'AW', name: 'Aruba', urlAliases: ['aw', 'aruba'] },
  { code: 'AZ', name: 'Azerbaijan', urlAliases: ['az', 'azerbaijan'] },
  { code: 'BA', name: 'Bosnia and Herzegovina', urlAliases: ['ba', 'bosnia-and-herzegovina'] },
  { code: 'BB', name: 'Barbados', urlAliases: ['bb', 'barbados'] },
  { code: 'BD', name: 'Bangladesh', urlAliases: ['bd', 'bangladesh'] },
  { code: 'BE', name: 'Belgium', urlAliases: ['be', 'belgium'] },
  { code: 'BF', name: 'Burkina Faso', urlAliases: ['bf', 'burkina-faso'] },
  { code: 'BG', name: 'Bulgaria', urlAliases: ['bg', 'bulgaria'] },
  { code: 'BH', name: 'Bahrain', urlAliases: ['bh', 'bahrain'] },
  { code: 'BI', name: 'Burundi', urlAliases: ['bi', 'burundi'] },
  { code: 'BJ', name: 'Benin', urlAliases: ['bj', 'benin'] },
  { code: 'BM', name: 'Bermuda', urlAliases: ['bm', 'bermuda'] },
  { code: 'BN', name: 'Brunei', urlAliases: ['bn', 'brunei'] },
  { code: 'BO', name: 'Bolivia', urlAliases: ['bo', 'bolivia'] },
  { code: 'BR', name: 'Brazil', urlAliases: ['br', 'brazil'] },
  { code: 'BS', name: 'Bahamas', urlAliases: ['bs', 'bahamas'] },
  { code: 'BT', name: 'Bhutan', urlAliases: ['bt', 'bhutan'] },
  { code: 'BV', name: 'Bouvet Island', urlAliases: ['bv', 'bouvet-island'] },
  { code: 'BW', name: 'Botswana', urlAliases: ['bw', 'botswana'] },
  { code: 'BY', name: 'Belarus', urlAliases: ['by', 'belarus'] },
  { code: 'BZ', name: 'Belize', urlAliases: ['bz', 'belize'] },
  { code: 'CA', name: 'Canada', urlAliases: ['ca', 'canada'] },
  { code: 'CC', name: 'Cocos [Keeling] Islands', urlAliases: ['cc', 'cocos-keeling-islands'] },
  { code: 'CD', name: 'Congo [DRC]', urlAliases: ['cd', 'congo [drc]'] },
  { code: 'CF', name: 'Central African Republic', urlAliases: ['cf', 'central-african-republic'] },
  { code: 'CG', name: 'Congo [Republic]', urlAliases: ['cg', 'congo-republic'] },
  { code: 'CH', name: 'Switzerland', urlAliases: ['ch', 'switzerland'] },
  { code: 'CI', name: 'Côte d\'\'Ivoire', urlAliases: ['ci', 'côte-d-ivoire'] },
  { code: 'CK', name: 'Cook Islands', urlAliases: ['ck', 'cook-islands'] },
  { code: 'CL', name: 'Chile', urlAliases: ['cl', 'chile'] },
  { code: 'CM', name: 'Cameroon', urlAliases: ['cm', 'cameroon'] },
  { code: 'CN', name: 'China', urlAliases: ['cn', 'china'] },
  { code: 'CO', name: 'Colombia', urlAliases: ['co', 'colombia'] },
  { code: 'CR', name: 'Costa Rica', urlAliases: ['cr', 'costa-rica'] },
  { code: 'CU', name: 'Cuba', urlAliases: ['cu', 'cuba'] },
  { code: 'CV', name: 'Cape Verde', urlAliases: ['cv', 'cape-verde'] },
  { code: 'CX', name: 'Christmas Island', urlAliases: ['cx', 'christmas-island'] },
  { code: 'CY', name: 'Cyprus', urlAliases: ['cy', 'cyprus'] },
  { code: 'CZ', name: 'Czech Republic', urlAliases: ['cz', 'czech-republic'] },
  { code: 'DE', name: 'Germany', urlAliases: ['de', 'germany'] },
  { code: 'DJ', name: 'Djibouti', urlAliases: ['dj', 'djibouti'] },
  { code: 'DK', name: 'Denmark', urlAliases: ['dk', 'denmark'] },
  { code: 'DM', name: 'Dominica', urlAliases: ['dm', 'dominica'] },
  { code: 'DO', name: 'Dominican Republic', urlAliases: ['do', 'dominican-republic'] },
  { code: 'DZ', name: 'Algeria', urlAliases: ['dz', 'algeria'] },
  { code: 'EC', name: 'Ecuador', urlAliases: ['ec', 'ecuador'] },
  { code: 'EE', name: 'Estonia', urlAliases: ['ee', 'estonia'] },
  { code: 'EG', name: 'Egypt', urlAliases: ['eg', 'egypt'] },
  { code: 'EH', name: 'Western Sahara', urlAliases: ['eh', 'western-sahara'] },
  { code: 'ER', name: 'Eritrea', urlAliases: ['er', 'eritrea'] },
  { code: 'ES', name: 'Spain', urlAliases: ['es', 'spain'] },
  { code: 'ET', name: 'Ethiopia', urlAliases: ['et', 'ethiopia'] },
  { code: 'FI', name: 'Finland', urlAliases: ['fi', 'finland'] },
  { code: 'FJ', name: 'Fiji', urlAliases: ['fj', 'fiji'] },
  {
    code: 'FK',
    name: 'Falkland Islands [Islas Malvinas]',
    urlAliases: ['fk', 'falkland-islands-islas-malvinas']
  },
  { code: 'FM', name: 'Micronesia', urlAliases: ['fm', 'micronesia'] },
  { code: 'FO', name: 'Faroe Islands', urlAliases: ['fo', 'faroe-islands'] },
  { code: 'FR', name: 'France', urlAliases: ['fr', 'france'] },
  { code: 'GA', name: 'Gabon', urlAliases: ['ga', 'gabon'] },
  { code: 'GB', name: 'United Kingdom', urlAliases: ['gb', 'united-kingdom'] },
  { code: 'GD', name: 'Grenada', urlAliases: ['gd', 'grenada'] },
  { code: 'GE', name: 'Georgia', urlAliases: ['ge', 'georgia'] },
  { code: 'GF', name: 'French Guiana', urlAliases: ['gf', 'french-guiana'] },
  { code: 'GG', name: 'Guernsey', urlAliases: ['gg', 'guernsey'] },
  { code: 'GH', name: 'Ghana', urlAliases: ['gh', 'ghana'] },
  { code: 'GI', name: 'Gibraltar', urlAliases: ['gi', 'gibraltar'] },
  { code: 'GL', name: 'Greenland', urlAliases: ['gl', 'greenland'] },
  { code: 'GM', name: 'Gambia', urlAliases: ['gm', 'gambia'] },
  { code: 'GN', name: 'Guinea', urlAliases: ['gn', 'guinea'] },
  { code: 'GP', name: 'Guadeloupe', urlAliases: ['gp', 'guadeloupe'] },
  { code: 'GQ', name: 'Equatorial Guinea', urlAliases: ['gq', 'equatorial-guinea'] },
  { code: 'GR', name: 'Greece', urlAliases: ['gr', 'greece'] },
  {
    code: 'GS',
    name: 'South Georgia and the South Sandwich Islands',
    urlAliases: ['gs', 'south-georgia-and-the-south-sandwich-islands']
  },
  { code: 'GT', name: 'Guatemala', urlAliases: ['gt', 'guatemala'] },
  { code: 'GU', name: 'Guam', urlAliases: ['gu', 'guam'] },
  { code: 'GW', name: 'Guinea-Bissau', urlAliases: ['gw', 'guinea-bissau'] },
  { code: 'GY', name: 'Guyana', urlAliases: ['gy', 'guyana'] },
  { code: 'GZ', name: 'Gaza Strip', urlAliases: ['gz', 'gaza-strip'] },
  { code: 'HK', name: 'Hong Kong', urlAliases: ['hk', 'hong-kong'] },
  {
    code: 'HM',
    name: 'Heard Island and McDonald Islands',
    urlAliases: ['hm', 'heard-island-and-mcdonald-islands']
  },
  { code: 'HN', name: 'Honduras', urlAliases: ['hn', 'honduras'] },
  { code: 'HR', name: 'Croatia', urlAliases: ['hr', 'croatia'] },
  { code: 'HT', name: 'Haiti', urlAliases: ['ht', 'haiti'] },
  { code: 'HU', name: 'Hungary', urlAliases: ['hu', 'hungary'] },
  { code: 'ID', name: 'Indonesia', urlAliases: ['id', 'indonesia'] },
  { code: 'IE', name: 'Ireland', urlAliases: ['ie', 'ireland'] },
  { code: 'IL', name: 'Israel', urlAliases: ['il', 'israel'] },
  { code: 'IM', name: 'Isle of Man', urlAliases: ['im', 'isle-of-man'] },
  { code: 'IN', name: 'India', urlAliases: ['in', 'india'] },
  {
    code: 'IO',
    name: 'British Indian Ocean Territory',
    urlAliases: ['io', 'british-indian-ocean-territory']
  },
  { code: 'IQ', name: 'Iraq', urlAliases: ['iq', 'iraq'] },
  { code: 'IR', name: 'Iran', urlAliases: ['ir', 'iran'] },
  { code: 'IS', name: 'Iceland', urlAliases: ['is', 'iceland'] },
  { code: 'IT', name: 'Italy', urlAliases: ['it', 'italy'] },
  { code: 'JE', name: 'Jersey', urlAliases: ['je', 'jersey'] },
  { code: 'JM', name: 'Jamaica', urlAliases: ['jm', 'jamaica'] },
  { code: 'JO', name: 'Jordan', urlAliases: ['jo', 'jordan'] },
  { code: 'JP', name: 'Japan', urlAliases: ['jp', 'japan'] },
  { code: 'KE', name: 'Kenya', urlAliases: ['ke', 'kenya'] },
  { code: 'KG', name: 'Kyrgyzstan', urlAliases: ['kg', 'kyrgyzstan'] },
  { code: 'KH', name: 'Cambodia', urlAliases: ['kh', 'cambodia'] },
  { code: 'KI', name: 'Kiribati', urlAliases: ['ki', 'kiribati'] },
  { code: 'KM', name: 'Comoros', urlAliases: ['km', 'comoros'] },
  { code: 'KN', name: 'Saint Kitts and Nevis', urlAliases: ['kn', 'saint-kitts-and-nevis'] },
  { code: 'KP', name: 'North Korea', urlAliases: ['kp', 'north-korea'] },
  { code: 'KR', name: 'South Korea', urlAliases: ['kr', 'south-korea'] },
  { code: 'KW', name: 'Kuwait', urlAliases: ['kw', 'kuwait'] },
  { code: 'KY', name: 'Cayman Islands', urlAliases: ['ky', 'cayman-islands'] },
  { code: 'KZ', name: 'Kazakhstan', urlAliases: ['kz', 'kazakhstan'] },
  { code: 'LA', name: 'Laos', urlAliases: ['la', 'laos'] },
  { code: 'LB', name: 'Lebanon', urlAliases: ['lb', 'lebanon'] },
  { code: 'LC', name: 'Saint Lucia', urlAliases: ['lc', 'saint-lucia'] },
  { code: 'LI', name: 'Liechtenstein', urlAliases: ['li', 'liechtenstein'] },
  { code: 'LK', name: 'Sri Lanka', urlAliases: ['lk', 'sri-lanka'] },
  { code: 'LR', name: 'Liberia', urlAliases: ['lr', 'liberia'] },
  { code: 'LS', name: 'Lesotho', urlAliases: ['ls', 'lesotho'] },
  { code: 'LT', name: 'Lithuania', urlAliases: ['lt', 'lithuania'] },
  { code: 'LU', name: 'Luxembourg', urlAliases: ['lu', 'luxembourg'] },
  { code: 'LV', name: 'Latvia', urlAliases: ['lv', 'latvia'] },
  { code: 'LY', name: 'Libya', urlAliases: ['ly', 'libya'] },
  { code: 'MA', name: 'Morocco', urlAliases: ['ma', 'morocco'] },
  { code: 'MC', name: 'Monaco', urlAliases: ['mc', 'monaco'] },
  { code: 'MD', name: 'Moldova', urlAliases: ['md', 'moldova'] },
  { code: 'ME', name: 'Montenegro', urlAliases: ['me', 'montenegro'] },
  { code: 'MG', name: 'Madagascar', urlAliases: ['mg', 'madagascar'] },
  { code: 'MH', name: 'Marshall Islands', urlAliases: ['mh', 'marshall-islands'] },
  { code: 'MK', name: 'Macedonia [FYROM]', urlAliases: ['mk', 'macedonia-fyrom'] },
  { code: 'ML', name: 'Mali', urlAliases: ['ml', 'mali'] },
  { code: 'MM', name: 'Myanmar [Burma]', urlAliases: ['mm', 'myanmar-burma'] },
  { code: 'MN', name: 'Mongolia', urlAliases: ['mn', 'mongolia'] },
  { code: 'MO', name: 'Macau', urlAliases: ['mo', 'macau'] },
  { code: 'MP', name: 'Northern Mariana Islands', urlAliases: ['mp', 'northern-mariana-islands'] },
  { code: 'MQ', name: 'Martinique', urlAliases: ['mq', 'martinique'] },
  { code: 'MR', name: 'Mauritania', urlAliases: ['mr', 'mauritania'] },
  { code: 'MS', name: 'Montserrat', urlAliases: ['ms', 'montserrat'] },
  { code: 'MT', name: 'Malta', urlAliases: ['mt', 'malta'] },
  { code: 'MU', name: 'Mauritius', urlAliases: ['mu', 'mauritius'] },
  { code: 'MV', name: 'Maldives', urlAliases: ['mv', 'maldives'] },
  { code: 'MW', name: 'Malawi', urlAliases: ['mw', 'malawi'] },
  { code: 'MX', name: 'Mexico', urlAliases: ['mx', 'mexico'] },
  { code: 'MY', name: 'Malaysia', urlAliases: ['my', 'malaysia'] },
  { code: 'MZ', name: 'Mozambique', urlAliases: ['mz', 'mozambique'] },
  { code: 'NA', name: 'Namibia', urlAliases: ['na', 'namibia'] },
  { code: 'NC', name: 'New Caledonia', urlAliases: ['nc', 'new-caledonia'] },
  { code: 'NE', name: 'Niger', urlAliases: ['ne', 'niger'] },
  { code: 'NF', name: 'Norfolk Island', urlAliases: ['nf', 'norfolk-island'] },
  { code: 'NG', name: 'Nigeria', urlAliases: ['ng', 'nigeria'] },
  { code: 'NI', name: 'Nicaragua', urlAliases: ['ni', 'nicaragua'] },
  { code: 'NL', name: 'Netherlands', urlAliases: ['nl', 'netherlands'] },
  { code: 'NO', name: 'Norway', urlAliases: ['no', 'norway'] },
  { code: 'NP', name: 'Nepal', urlAliases: ['np', 'nepal'] },
  { code: 'NR', name: 'Nauru', urlAliases: ['nr', 'nauru'] },
  { code: 'NU', name: 'Niue', urlAliases: ['nu', 'niue'] },
  { code: 'NZ', name: 'New Zealand', urlAliases: ['nz', 'new-zealand'] },
  { code: 'OM', name: 'Oman', urlAliases: ['om', 'oman'] },
  { code: 'PA', name: 'Panama', urlAliases: ['pa', 'panama'] },
  { code: 'PE', name: 'Peru', urlAliases: ['pe', 'peru'] },
  { code: 'PF', name: 'French Polynesia', urlAliases: ['pf', 'french-polynesia'] },
  { code: 'PG', name: 'Papua New Guinea', urlAliases: ['pg', 'papua-new-guinea'] },
  { code: 'PH', name: 'Philippines', urlAliases: ['ph', 'philippines'] },
  { code: 'PK', name: 'Pakistan', urlAliases: ['pk', 'pakistan'] },
  { code: 'PL', name: 'Poland', urlAliases: ['pl', 'poland'] },
  {
    code: 'PM',
    name: 'Saint Pierre and Miquelon',
    urlAliases: ['pm', 'saint-pierre-and-miquelon']
  },
  { code: 'PN', name: 'Pitcairn Islands', urlAliases: ['pn', 'pitcairn-islands'] },
  { code: 'PR', name: 'Puerto Rico', urlAliases: ['pr', 'puerto-rico'] },
  { code: 'PS', name: 'Palestinian Territories', urlAliases: ['ps', 'palestinian-territories'] },
  { code: 'PT', name: 'Portugal', urlAliases: ['pt', 'portugal'] },
  { code: 'PW', name: 'Palau', urlAliases: ['pw', 'palau'] },
  { code: 'PY', name: 'Paraguay', urlAliases: ['py', 'paraguay'] },
  { code: 'QA', name: 'Qatar', urlAliases: ['qa', 'qatar'] },
  { code: 'RE', name: 'Réunion', urlAliases: ['re', 'réunion'] },
  { code: 'RO', name: 'Romania', urlAliases: ['ro', 'romania'] },
  { code: 'RS', name: 'Serbia', urlAliases: ['rs', 'serbia'] },
  { code: 'RU', name: 'Russia', urlAliases: ['ru', 'russia'] },
  { code: 'RW', name: 'Rwanda', urlAliases: ['rw', 'rwanda'] },
  { code: 'SA', name: 'Saudi Arabia', urlAliases: ['sa', 'saudi-arabia'] },
  { code: 'SB', name: 'Solomon Islands', urlAliases: ['sb', 'solomon-islands'] },
  { code: 'SC', name: 'Seychelles', urlAliases: ['sc', 'seychelles'] },
  { code: 'SD', name: 'Sudan', urlAliases: ['sd', 'sudan'] },
  { code: 'SE', name: 'Sweden', urlAliases: ['se', 'sweden'] },
  { code: 'SG', name: 'Singapore', urlAliases: ['sg', 'singapore'] },
  { code: 'SH', name: 'Saint Helena', urlAliases: ['sh', 'saint-helena'] },
  { code: 'SI', name: 'Slovenia', urlAliases: ['si', 'slovenia'] },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', urlAliases: ['sj', 'svalbard-and-jan-mayen'] },
  { code: 'SK', name: 'Slovakia', urlAliases: ['sk', 'slovakia'] },
  { code: 'SL', name: 'Sierra Leone', urlAliases: ['sl', 'sierra-leone'] },
  { code: 'SM', name: 'San Marino', urlAliases: ['sm', 'san-marino'] },
  { code: 'SN', name: 'Senegal', urlAliases: ['sn', 'senegal'] },
  { code: 'SO', name: 'Somalia', urlAliases: ['so', 'somalia'] },
  { code: 'SR', name: 'Suriname', urlAliases: ['sr', 'suriname'] },
  { code: 'ST', name: 'São Tomé and Príncipe', urlAliases: ['st', 'são-tomé-and-príncipe'] },
  { code: 'SV', name: 'El Salvador', urlAliases: ['sv', 'el-salvador'] },
  { code: 'SY', name: 'Syria', urlAliases: ['sy', 'syria'] },
  { code: 'SZ', name: 'Swaziland', urlAliases: ['sz', 'swaziland'] },
  { code: 'TC', name: 'Turks and Caicos Islands', urlAliases: ['tc', 'turks-and-caicos-islands'] },
  { code: 'TD', name: 'Chad', urlAliases: ['td', 'chad'] },
  {
    code: 'TF',
    name: 'French Southern Territories',
    urlAliases: ['tf', 'french-southern-territories']
  },
  { code: 'TG', name: 'Togo', urlAliases: ['tg', 'togo'] },
  { code: 'TH', name: 'Thailand', urlAliases: ['th', 'thailand'] },
  { code: 'TJ', name: 'Tajikistan', urlAliases: ['tj', 'tajikistan'] },
  { code: 'TK', name: 'Tokelau', urlAliases: ['tk', 'tokelau'] },
  { code: 'TL', name: 'Timor-Leste', urlAliases: ['tl', 'timor-leste'] },
  { code: 'TM', name: 'Turkmenistan', urlAliases: ['tm', 'turkmenistan'] },
  { code: 'TN', name: 'Tunisia', urlAliases: ['tn', 'tunisia'] },
  { code: 'TO', name: 'Tonga', urlAliases: ['to', 'tonga'] },
  { code: 'TR', name: 'Turkey', urlAliases: ['tr', 'turkey'] },
  { code: 'TT', name: 'Trinidad and Tobago', urlAliases: ['tt', 'trinidad-and-tobago'] },
  { code: 'TV', name: 'Tuvalu', urlAliases: ['tv', 'tuvalu'] },
  { code: 'TW', name: 'Taiwan', urlAliases: ['tw', 'taiwan'] },
  { code: 'TZ', name: 'Tanzania', urlAliases: ['tz', 'tanzania'] },
  { code: 'UA', name: 'Ukraine', urlAliases: ['ua', 'ukraine'] },
  { code: 'UG', name: 'Uganda', urlAliases: ['ug', 'uganda'] },
  {
    code: 'UM',
    name: 'U.S. Minor Outlying Islands',
    urlAliases: ['um', 'us-minor-outlying-islands']
  },
  { code: 'US', name: 'United States', urlAliases: ['us', 'united-states'] },
  { code: 'UY', name: 'Uruguay', urlAliases: ['uy', 'uruguay'] },
  { code: 'UZ', name: 'Uzbekistan', urlAliases: ['uz', 'uzbekistan'] },
  { code: 'VA', name: 'Vatican City', urlAliases: ['va', 'vatican-city'] },
  {
    code: 'VC',
    name: 'Saint Vincent and the Grenadines',
    urlAliases: ['vc', 'saint-vincent-and-the-grenadines']
  },
  { code: 'VE', name: 'Venezuela', urlAliases: ['ve', 'venezuela'] },
  { code: 'VG', name: 'British Virgin Islands', urlAliases: ['vg', 'british-virgin-islands'] },
  { code: 'VI', name: 'U.S. Virgin Islands', urlAliases: ['vi', 'us-virgin-islands'] },
  { code: 'VN', name: 'Vietnam', urlAliases: ['vn', 'vietnam'] },
  { code: 'VU', name: 'Vanuatu', urlAliases: ['vu', 'vanuatu'] },
  { code: 'WF', name: 'Wallis and Futuna', urlAliases: ['wf', 'wallis-and-futuna'] },
  { code: 'WS', name: 'Samoa', urlAliases: ['ws', 'samoa'] },
  { code: 'XK', name: 'Kosovo', urlAliases: ['xk', 'kosovo'] },
  { code: 'YE', name: 'Yemen', urlAliases: ['ye', 'yemen'] },
  { code: 'YT', name: 'Mayotte', urlAliases: ['yt', 'mayotte'] },
  { code: 'ZA', name: 'South Africa', urlAliases: ['za', 'south-africa'] },
  { code: 'ZM', name: 'Zambia', urlAliases: ['zm', 'zambia'] },
  { code: 'ZW', name: 'Zimbabwe', urlAliases: ['zw', 'zimbabwe'] },
  { code: 'CI', name: 'Ivory Coast', urlAliases: ['ci', 'ivory-coast'] },
];

export const defaultLocale = 'en';
export const locales = [
  {
    code: 'en',
    name: 'English',
    file: 'en.js',
  },
  {
    code: 'ms',
    name: 'Bahasa Melayu',
    file: 'ms.js',
  },
  {
    code: 'ptbr',
    name: 'Português (Brasil)',
    file: 'pt-br.js',
  },
  {
    code: 'vi',
    name: 'Tiếng Việt',
    file: 'vi.js',
  },
  {
    code: 'ar',
    name: 'العربية',
    file: 'ar.js',
  },
];
